name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx ts-prune || echo "ts-prune warnings ignored in PR checks"
      - run: npm run lint
      - run: npx tsc --noEmit

  smoke:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Set npm registry (CI)
        run: npm config set registry https://registry.npmjs.org/
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run smoke tests against production
        env:
          BASE_URL: https://nextgendashboard.trecasa.com
        run: npm run smoke
